name: Create File List for ESL Homepage

on:
  schedule:
    - cron: "0 8 * * 0"
  workflow_dispatch:
  

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Install dependencies required by the scripts
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aptly awscli python3-pip
          pip3 install boto3
      # Configure Credentials for AWS    
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.2
        with:
          version: 2 # default
          verbose: false # default
          arch: amd64
          
       # Run python script for create the JSON Files for each Product 
      - name: Generate new Erlang  JSON files for ESL Homepage
        run: | 
          python3 file_list_creator.py
          aws s3 sync . s3://binaries2.erlang-solutions.com --acl public-read --exclude "*" --include "*.json"
          
      # Run python script for create the JSON Files for Elixir Product 
      - name: Generate new Elixir JSON files for ESL Homepage
        run: | 
          python3 file_list_creator_elixir.py
          aws s3 sync . s3://binaries2.erlang-solutions.com --acl public-read --exclude "*" --include "*.json"

      # Run python script for create the JSON Files for MIM Product 
      - name: Generate new MongooseIM JSON files for ESL Homepage
        run: | 
          python3 file_list_creator_mongooseim.py
          aws s3 sync . s3://binaries2.erlang-solutions.com --acl public-read --exclude "*" --include "*.json"
        
